[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "story-flicks"
version = "0.1.0"
description = "Story Flicks Backend"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["backend"]
